package net.doge.constants;

import net.doge.models.UIStyle;

/**
 * @Author yzx
 * @Description 预设样式
 * @Date 2020/12/12
 */
public class PreDefinedUIStyle {
    public static final UIStyle[] styles = {
            new UIStyle(UIStyleConstants.PRE, "默认", SimplePath.STYLE_IMG_PATH + "default.jpg",
                    Colors.LIGHT_GRAY, Colors.GRAY, Colors.WHITE, Colors.DEEP_SKY_BLUE_1, Colors.WHITE,
                    Colors.LIGHT_GRAY, Colors.LIGHT_GRAY, Colors.LIGHT_GRAY, Colors.LIGHT_GRAY, Colors.LIGHT_GRAY, Colors.LIGHT_GRAY),
            new UIStyle(UIStyleConstants.PRE, "白天", SimplePath.STYLE_IMG_PATH + "day.jpg",
                    Colors.WHITE_SMOKE, Colors.DAY2, Colors.WHITE, Colors.DAY3, Colors.WHITE_SMOKE,
                    Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE),
            new UIStyle(UIStyleConstants.PRE, "夜晚", SimplePath.STYLE_IMG_PATH + "night.jpg",
                    Colors.LEMON_CHIFFON, Colors.GOLD, Colors.LEMON_CHIFFON, Colors.GOLD3, Colors.LEMON_CHIFFON,
                    Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON),
            new UIStyle(UIStyleConstants.PRE, "春", SimplePath.STYLE_IMG_PATH + "spring.jpg",
                    Colors.SPRING1, Colors.SPRING2, Colors.SPRING1, Colors.SPRING3, Colors.SPRING1,
                    Colors.SPRING1, Colors.SPRING1, Colors.SPRING1, Colors.SPRING1, Colors.SPRING1, Colors.SPRING1),
            new UIStyle(UIStyleConstants.PRE, "夏", SimplePath.STYLE_IMG_PATH + "summer.jpg",
                    Colors.SUMMER1, Colors.SUMMER2, Colors.SUMMER1, Colors.SUMMER3, Colors.SUMMER1,
                    Colors.SUMMER1, Colors.SUMMER1, Colors.SUMMER1, Colors.SUMMER1, Colors.SUMMER1, Colors.SUMMER1),
            new UIStyle(UIStyleConstants.PRE, "秋", SimplePath.STYLE_IMG_PATH + "autumn.jpg",
                    Colors.LEMON_CHIFFON, Colors.GOLD, Colors.LEMON_CHIFFON, Colors.GOLD3, Colors.LEMON_CHIFFON,
                    Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON, Colors.LEMON_CHIFFON),
            new UIStyle(UIStyleConstants.PRE, "冬", SimplePath.STYLE_IMG_PATH + "winter.jpg",
                    Colors.WHITE, Colors.CLOUD2, Colors.WHITE, Colors.CLOUD3, Colors.WHITE,
                    Colors.WHITE, Colors.WHITE, Colors.WHITE, Colors.WHITE, Colors.WHITE, Colors.WHITE),
            new UIStyle(UIStyleConstants.PRE, "粉红天堂", SimplePath.STYLE_IMG_PATH + "pinkParadise.jpg",
                    Colors.PINK1, Colors.PINK2, Colors.PINK1, Colors.PINK3, Colors.PINK1,
                    Colors.PINK1, Colors.PINK1, Colors.PINK1, Colors.PINK1, Colors.PINK1, Colors.PINK1),
            new UIStyle(UIStyleConstants.PRE, "极简主义", SimplePath.STYLE_IMG_PATH + "minimalism.jpg",
                    Colors.MINIMALISM1, Colors.MINIMALISM2, Colors.MINIMALISM1, Colors.MINIMALISM3, Colors.MINIMALISM1,
                    Colors.MINIMALISM1, Colors.MINIMALISM1, Colors.MINIMALISM1, Colors.MINIMALISM1, Colors.MINIMALISM1, Colors.MINIMALISM1),
            new UIStyle(UIStyleConstants.PRE, "抽象风景", SimplePath.STYLE_IMG_PATH + "abstractLandscape.jpg",
                    Colors.AL1, Colors.AL2, Colors.AL1, Colors.AL3, Colors.AL1,
                    Colors.AL1, Colors.AL1, Colors.AL1, Colors.AL1, Colors.AL1, Colors.AL1),
            new UIStyle(UIStyleConstants.PRE, "落日海洋", SimplePath.STYLE_IMG_PATH + "sunsetOcean.jpg",
                    Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN2, Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN3, Colors.SUNSET_OCEAN1,
                    Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN1, Colors.SUNSET_OCEAN1),
            new UIStyle(UIStyleConstants.PRE, "落日星空", SimplePath.STYLE_IMG_PATH + "starrySunset.jpg",
                    Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET2, Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET3, Colors.STARRY_SUNSET1,
                    Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET1, Colors.STARRY_SUNSET1),
            new UIStyle(UIStyleConstants.PRE, "她", SimplePath.STYLE_IMG_PATH + "she.jpg",
                    Colors.BISQUE_1, Colors.BISQUE_3, Colors.BISQUE_1, Colors.CYAN_3, Colors.BISQUE_1,
                    Colors.BISQUE_1, Colors.BISQUE_1, Colors.BISQUE_1, Colors.BISQUE_1, Colors.BISQUE_1, Colors.BISQUE_1),
            new UIStyle(UIStyleConstants.PRE, "鹿鸣", SimplePath.STYLE_IMG_PATH + "luming.jpg",
                    Colors.AQUAMARINE_1, Colors.AQUAMARINE_3, Colors.AQUAMARINE_1, Colors.SPRING_GREEN, Colors.AQUAMARINE_1,
                    Colors.AQUAMARINE_1, Colors.AQUAMARINE_1, Colors.AQUAMARINE_1, Colors.AQUAMARINE_1, Colors.AQUAMARINE_1, Colors.AQUAMARINE_1),
            new UIStyle(UIStyleConstants.PRE, "你的名字", SimplePath.STYLE_IMG_PATH + "yourName.jpg",
                    Colors.THISTLE_1, Colors.ORCHID_2, Colors.THISTLE_1, Colors.ORCHID_2, Colors.THISTLE_1,
                    Colors.THISTLE_1, Colors.THISTLE_1, Colors.THISTLE_1, Colors.THISTLE_1, Colors.THISTLE_1, Colors.THISTLE_1),
            new UIStyle(UIStyleConstants.PRE, "深海", SimplePath.STYLE_IMG_PATH + "deepSea.jpg",
                    Colors.LIGHT_SKY_BLUE_1, Colors.DEEP_SKY_BLUE_1, Colors.LIGHT_SKY_BLUE_1, Colors.DEEP_SKY_BLUE_3, Colors.LIGHT_SKY_BLUE_1,
                    Colors.LIGHT_SKY_BLUE_1, Colors.LIGHT_SKY_BLUE_1, Colors.LIGHT_SKY_BLUE_1, Colors.LIGHT_SKY_BLUE_1, Colors.LIGHT_SKY_BLUE_1, Colors.LIGHT_SKY_BLUE_1),
            new UIStyle(UIStyleConstants.PRE, "林间小溪", SimplePath.STYLE_IMG_PATH + "brook.jpg",
                    Colors.KHAKI_1, Colors.ORANGE_1, Colors.KHAKI_1, Colors.ORANGE_1, Colors.KHAKI_1,
                    Colors.KHAKI_1, Colors.KHAKI_1, Colors.KHAKI_1, Colors.KHAKI_1, Colors.KHAKI_1, Colors.KHAKI_1),
            new UIStyle(UIStyleConstants.PRE, "新年快乐", SimplePath.STYLE_IMG_PATH + "happyNewYear.jpg",
                    Colors.MISTY_ROSE, Colors.CHINESE_RED_2, Colors.MISTY_ROSE, Colors.CHINESE_RED_2, Colors.MISTY_ROSE,
                    Colors.MISTY_ROSE, Colors.MISTY_ROSE, Colors.MISTY_ROSE, Colors.MISTY_ROSE, Colors.MISTY_ROSE, Colors.MISTY_ROSE),
            new UIStyle(UIStyleConstants.PRE, "犬塚信乃戍孝", SimplePath.STYLE_IMG_PATH + "moritaka.jpg",
                    Colors.LIGHT_BLUE_1, Colors.ORANGE_1, Colors.LIGHT_BLUE_1, Colors.ORANGE_1, Colors.LIGHT_BLUE_1,
                    Colors.LIGHT_BLUE_1, Colors.LIGHT_BLUE_1, Colors.LIGHT_BLUE_1, Colors.LIGHT_BLUE_1, Colors.LIGHT_BLUE_1, Colors.LIGHT_BLUE_1),
            new UIStyle(UIStyleConstants.PRE, "戍孝与雨", SimplePath.STYLE_IMG_PATH + "moritakaAndRain.jpg",
                    Colors.WHITE_SMOKE, Colors.BISQUE_2, Colors.WHITE_SMOKE, Colors.BISQUE_3, Colors.WHITE_SMOKE,
                    Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE, Colors.WHITE_SMOKE),
            new UIStyle(UIStyleConstants.PRE, "云间小憩", SimplePath.STYLE_IMG_PATH + "cloudRest.jpg",
                    Colors.CLOUD1, Colors.CLOUD2, Colors.CLOUD1, Colors.CLOUD3, Colors.CLOUD1,
                    Colors.CLOUD1, Colors.CLOUD1, Colors.CLOUD1, Colors.CLOUD1, Colors.CLOUD1, Colors.CLOUD1)
    };
}
